[package]
name = "download_bikes"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.29", features = ["rt-multi-thread", "macros", "fs"] }
reqwest = { version = "0.12.25", features = ["gzip", "brotli", "deflate", "stream"] }
futures = "0.3"
clap = { version = "4.2", features = ["derive"] }
num_cpus = "1.16"
zip = "6.0.0"